### ISSUE TITLE
replace back stairs

### ISSUE THREAD

**Issue by zippy** [zippy/jungle-laser#16]
House appreciates stairs in good repair with safe railings

The back stairs are rotting and the railing is wobbly.  The whole thing needs replacement, and the plaster under the lip of the door also needs redoing.

Note: redid the plaster once and it didn't work well, need a different strategy.  Part of the issue is that force of stepping on the door lip transfers into the plaster so need some top layer of rubber (or just silicone caulk) or something that can seal to prevent water from getting behind plaster, but all have some give.

**Comment by qubist** [comment]
@MorvinBear and I unscrewed and removed the rail

**Comment by zippy** [comment]
![Uploading IMG-20200823-WA0009.jpeg…](Treads!)

**Comment by zippy** [comment]
![Uploading IMG-20200823-WA0009.jpeg…](Treads!)

**Comment by zippy** [comment]
![IMG-20200823-WA0009](https://user-images.githubusercontent.com/3563/90989703-f3a19080-e569-11ea-8840-50ee53f63d91.jpeg)
![IMG-20200823-WA0011](https://user-images.githubusercontent.com/3563/90989704-f43a2700-e569-11ea-9a6a-2da1571d5f99.jpeg)
Treads!

**Comment by zippy** [comment]
![IMG_20200906_103720](https://user-images.githubusercontent.com/3563/92401470-be657880-f0fb-11ea-8073-306e2426a769.jpg)
![IMG_20200907_110704](https://user-images.githubusercontent.com/3563/92401472-bf96a580-f0fb-11ea-9ad3-0d0fd85b8363.jpg)
Done!

**Comment by samcooley** [comment]
Beautiful.
