### ISSUE TITLE
JL yearns for movement: negentropize small stack of books

### ISSUE THREAD

**Issue by MorvinBear** [zippy/jungle-laser#17]
**JL yearns for movement**

There is a small stack of books, most of which do not get used that were entropizing on the music shelf, that resolving [this issue](https://github.com/zippy/jungle-laser/issues/5) surfaced. @zippy, will you please go through these or deputize someone else to do so? 

I have energy for it today, and cannot promise I will tomorrow. If it doesn't happen before I leave, I fear they will persists.

**Comment by zippy** [comment]
I sorted books into three piles, good-will, keep, and ?

**Comment by MorvinBear** [comment]
Keepers are on another shelf now. Goodwillers and ?'s (which I checked with Will on) will go to farmhouse.
