### ISSUE TITLE
leaderboarditis

### ISSUE THREAD

**Issue by MorvinBear** [zippy/jungle-laser#18]
Fuck. I'm getting swept up into do-stuff energy and am excited about it. This energy is a good thing, but, I'm catching myself now wanting to share about this other little project I did, to open a new issue and then solve it, for unslumping Artie-Duino and hanging him (not in a murder way) from a peg so that he's sitting more comfortably by suspension, and in a manner more pretty. So, I'm catching myself not wanting to share and open an issue. So, I'm sidestepping and making an issue out of the issue.  

How do we communicate with the Jungle Lasers in a way that's doesn't move in a leaderboardy direction?
At what level do we share, and celebrate movement without creating an atmosphere where people get all special-snowflakey about the representation of contribution?
What needs to be known by the house, what needs to be known by the house's peoples?

WWBnBD?
WWLD?

**Comment by zippy** [comment]
Love these questions.  Leaderboards are embodied forms where you focus on the statistics of who did what.  So we just don't make those embodied forms.  You can go back and count commits or issues and stuff, but it becomes a leaderboard when the board becomes an answer to the question "How do we know that we know".  Until then it's just data, which I think is fine.

**Comment by MorvinBear** [comment]
Okay.
