### ISSUE TITLE
Unslump Artie-Duino

### ISSUE THREAD

**Issue by MorvinBear** [zippy/jungle-laser#19]
He looks like shit, strings and manipulators akimbo on the music unit.

**Comment by MorvinBear** [comment]
![15818644087658475736563771288131](https://user-images.githubusercontent.com/2879930/74606801-4709c200-50a1-11ea-9acd-8b919907fe5c.jpg)

**Comment by JeanMRussell** [comment]
Thank you @MorvinBear
