### ISSUE TITLE
Organize Pantry

### ISSUE THREAD

**Issue by zippy** [zippy/jungle-laser#2]
Pantry needs clearing and organizing.

Acceptance Criteria:

- [x] bags organized and 
- [x] bottles dealt with
- [x] hanging stuff arranged or removed
- [x] pottery to basement or repaired
- [x] drawers and cupboards sorted and refreshed

**Comment by JeanMRussell** [comment]
Completed in 3 hours or less. 
Spices and seeds still need sorting. 
Did not discard, only arranged.
