### ISSUE TITLE
Add 3D printer

### ISSUE THREAD

**Issue by qubist** [zippy/jungle-laser#22]
https://shop.prusa3d.com/en/3d-printers/180-original-prusa-i3-mk3-kit.html#

Order status:
- [x] payment accepted
- [x] shipped
- [x] delivered

Next steps
- [x] assemble

**Comment by qubist** [comment]
Status update: assembled and working!!

![Image](https://user-images.githubusercontent.com/3607279/80006934-913d6400-8493-11ea-8829-9f0930f30025.jpeg)

**Comment by qubist** [comment]
closing issue, active and queued prints and ideas can be tracked here: https://github.com/zippy/jungle-laser/projects/1

**Comment by qubist** [comment]
# Pictures from the assembly process

![60917869673__D01110BA-E537-456A-82BF-FA871023E1ED](https://user-images.githubusercontent.com/3607279/80017350-79b9a780-84a2-11ea-8ccb-e4955a392656.JPG)
![60918027378__3B45D9CD-A74C-40B6-BD6D-7ABD4BFEA431](https://user-images.githubusercontent.com/3607279/80017351-7a523e00-84a2-11ea-8aa6-c2c0bb022df4.JPG)
![60918684103__CFA32F45-1851-4513-81AD-B75A189E908D](https://user-images.githubusercontent.com/3607279/80017353-7a523e00-84a2-11ea-9230-4b7e9202d207.JPG)
![60920149612__B1988B4F-E86F-4487-87DC-16EAA759DE28](https://user-images.githubusercontent.com/3607279/80017355-7a523e00-84a2-11ea-8489-443ad70294d0.JPG)
![60921907699__AF963AB8-07DA-48B8-A193-276A952DA48D](https://user-images.githubusercontent.com/3607279/80017357-7aead480-84a2-11ea-8ace-8e46a4349c48.JPG)
![60922141862__20DF124F-D6E6-443A-BAB4-29428B46BFE9](https://user-images.githubusercontent.com/3607279/80017358-7aead480-84a2-11ea-9797-277466a41a12.JPG)
![60922225567__0F159875-8A5C-491F-A55A-48169E15E88C](https://user-images.githubusercontent.com/3607279/80017359-7b836b00-84a2-11ea-9bb6-e7ceb056f57d.JPG)
![60922508957__4C5D3779-F332-4E5F-9ADF-F88F9D33F584](https://user-images.githubusercontent.com/3607279/80017361-7b836b00-84a2-11ea-9495-86abc84e3700.JPG)

**Comment by samcooley** [comment]
Amazing, I see the moccasins of one of the predators mentioned in step 42,
in one of the earlier photos.  Hope it all went well!

Sam
