### ISSUE TITLE
Lampshade for Fab room

### ISSUE THREAD

**Issue by qubist** [zippy/jungle-laser#24]
<img width="459" alt="Screen Shot 2020-04-23 at 10 05 07 AM" src="https://user-images.githubusercontent.com/3607279/80108096-e9cf3880-8549-11ea-9bcb-c1d04604f581.png">

**Comment by qubist** [comment]
designing a part that will clip onto the cable

**Comment by qubist** [comment]
Done! 
![Image](https://user-images.githubusercontent.com/3607279/80295552-9aebf380-8741-11ea-96d9-f0ad51c994f0.jpeg)

(yes, that's 3D printed, 2 lightbulbs fit inside, it took up the whole build plate!)

**Comment by samcooley** [comment]
Wow.

**Comment by qubist** [comment]
![60946623086__B885C2E2-6C4C-4ECB-A890-1EF1024B978F](https://user-images.githubusercontent.com/3607279/80319845-c114a080-87e0-11ea-8707-a8d1d6a639c4.JPG)
