### ISSUE TITLE
Hang Bass Guitars

### ISSUE THREAD

**Issue by zippy** [zippy/jungle-laser#3]
House appreciates guitars neatly organized and cared for.

- [x] research hanger types
- [x] decide
- [x] purchase/make
- [x] hang

**Comment by zippy** [comment]
Here are a two options that Jean found:

- wooden made elsewhere: https://www.etsy.com/listing/534332614/guitar-hanger  
- 3d printable: https://www.thingiverse.com/thing:2600335

@qubist, what do you think about 3d printable one?  Wanna print out some nice resin ones?

**Comment by JeanMRussell** [comment]
Location. 
![IMG_20200208_120419](https://user-images.githubusercontent.com/30393568/74106975-897b4e00-4b39-11ea-916b-d5d38d3ba446.jpg)

**Comment by zippy** [comment]
@qubist link fixed.

**Comment by qubist** [comment]
@zippy Do you know if your basses have "normal" size necks that will fit in these hangars? If not, we can scale them.

These look fine to print, I can do it with 1 week notice and ship them or bring them home next time.

**Comment by qubist** [comment]
I'm very in favor of printing vs. buying. + ooh maybe a little one for the ukulele if people want!

**Comment by JeanMRussell** [comment]
@qubist we did measure and the black one was right. (I was worried about it hanging crooked.) I think 2 inches? 
Measuring again, not only for width but also height and depth would be useful @zippy .

If the question is print or make from wood, which material is preferred? It looks like @zippy framed the question as print or buy the wood one; but, in the discussion we had, it sounded like making the wood one was an option. Of course, I have no preference, only a desire for clarity.

**Comment by qubist** [comment]
Currently at work. I'm going to, perhaps a bit brashly, print one or two of these! Will update.

**Comment by qubist** [comment]
![Image](https://user-images.githubusercontent.com/3607279/74593532-28042500-4ffa-11ea-870d-bc3ebbd6ad1e.jpeg)

Sliced in Cura with the following settings
* Wall line count: 4
* Infill density: 30%
* Layer height: 0.2mm

Print time: 7h7m
Material use prediction: 102g/12.9m

Printing in white PLA on an Ultimaker 3

**Comment by MorvinBear** [comment]
cool.

**Comment by qubist** [comment]
![Image](https://user-images.githubusercontent.com/3607279/74594930-d368a600-5009-11ea-9e09-f1d9302ae7dd.jpeg)

**Comment by qubist** [comment]
@zippy in response to your suggestion about resin: I have a feeling PLA is going to be stronger

**Comment by qubist** [comment]
Just picked up the print:

![Image](https://user-images.githubusercontent.com/3607279/74978008-cd076f00-53f9-11ea-8877-110a28f79912.jpeg)

Unfortunately it was weak and broke at the bottom of the Y due to what looks like a small printing error combined with a slight weak-point in the design. I will try to glue that part, otherwise print another with a smaller layer height.

@zippy or anyone, if you have a request for a different color, say so!

**Comment by qubist** [comment]
Glued pretty well.

**Comment by zippy** [comment]
Hmmm I think I would like to try a different color.  That white feels like it would stand out pretty starkly on the wood wall between the black bass, or the wood guitar.    Black maybe?  Is there a reasonable dark brown?

**Comment by MorvinBear** [comment]
A differenter ideas would be to make several cross-sections of this design, and then cut them out of several pieces of wood, then epoxy them together to make the same design, but out of wuud itself to blend gorgeously into the wooooodness of the house.

**Comment by qubist** [comment]
Hung it! 
![IMG_7094](https://user-images.githubusercontent.com/3607279/80007643-8a632100-8494-11ea-8167-e7ad197c3b3c.JPG)
![IMG_7093](https://user-images.githubusercontent.com/3607279/80007648-8b944e00-8494-11ea-8951-7552a69ffdfb.JPG)

Queued: some more hooks for the other guitar and the banjo

**Comment by MorvinBear** [comment]
Looks great.

BWAIDC
(Banjo Weight Anxiety Inducing Concern)

The banjo is much, much heavier than the guitars, since it has a gorgeous brass tone ring in it's tum-tum. @qubist  - can you please take care to either test or, maybe reinforce the the hook before trusting it with The Spirit of Baby Blue (testing out a name for the banjo).

I'm happy to do some porblem sloving with you about it. Maybe impregnating the hook with some epoxy (which I think there is some of in the basement)? Maybe filling it with molten bronze, but also inside of a mold so it retains the shape? Maybe fashioning something else? Maybe installing a reliably failsafe Rube Goldbergian contraption to catch and gently cradle it back into it's case should the hook fail catastrophically?

**Comment by qubist** [comment]
Currently printing second hook at 90% scale with our 5-year-old white PLA (slightly different color than currently installed one, but pretty close)

**Comment by qubist** [comment]
> can you please take care to either test or, maybe reinforce the the hook before trusting it with The Spirit of Baby Blue

Absolutely. We'll do extensive, peer-reviewed testing to make sure the hook can take the weight. Suspecting that it will, (they're pretty strong, w design based on the Strongest Shape™ (a triangle)) but I won't let this bias my Science Based Tests which i will use Equipment and Imperialism to make sure are objectively correct.

@MorvinBear

**Comment by MorvinBear** [comment]
Bless you and your Science Based Tests and you Equipment and Imperialism @qubist.

**Comment by qubist** [comment]
Idea: livestreaming camera from printer so everyone far and whide can se progres? :D

**Comment by qubist** [comment]
with contstant barkrcound music: https://www.youtube.com/watch?v=yxAnp26dfWg&list=TLPQMjMwNDIwMjDpITM94x0rVw&index=3

**Comment by qubist** [comment]
In loo of that, here's a pretty picture for all you watching at home:
![IMG_7103](https://user-images.githubusercontent.com/3607279/80125502-bbf4ee80-855f-11ea-979b-ba1cf862d75e.JPG)

**Comment by qubist** [comment]
@MorvinBear current plan is to print with very much infill and an extreme number of perimeters to make a Gnarly-strong part:

<img width="889" alt="Screen Shot 2020-04-23 at 11 21 42 PM" src="https://user-images.githubusercontent.com/3607279/80172017-d9ef3d00-85b9-11ea-8478-49b0282c994d.png">

**Comment by MorvinBear** [comment]
Sweet. Thank you.

**Comment by MorvinBear** [comment]
Sweet. Thank you @qubist.

**Comment by qubist** [comment]
![IMG_7119](https://user-images.githubusercontent.com/3607279/80295566-beaf3980-8741-11ea-8238-53858b5787db.JPG)

**Comment by qubist** [comment]
Make posted: https://www.thingiverse.com/make:875494
