### ISSUE TITLE
Take recycling out

### ISSUE THREAD

**Issue by JeanMRussell** [zippy/jungle-laser#8]
House appreciates removal of recycling from basement. Now stacked by back basement door.

**Comment by qubist** [comment]
**Knowledge from Afar Contribution for Holistic Awareness (KACHA):** A stack of flattened cardboard boxes is around that area. I stripped all the plastic off these to use them for gardening. They can be recycled, but work has been done to prepare them for that other use, which should be considered.

**Comment by MorvinBear** [comment]
How about we put the garden-able cardboard boxes under the porch, where they're unlikely to rot too much before use?

They can also be used for cultivating mycelium. I got some cultures of [Pycnoporus Cinnabarinus](https://healing-mushrooms.net/archives/pycnoporus-cinnabarinus.html), a gorgeous rare mushroom which I believe has potential for culture for medicinal and material purposes (it's, like, magnificently leathery, and they're making fungus leather out of far less orange fungi, which is dumb). 

I'm going to inoculate some of them with my stuff and hope that it works. Who knows.

IGtoBABB (I'm going to, perhaps a bit brashly,) put them under the porch and inoculate some.

**Comment by JeanMRussell** [comment]
So is there another set of tasks: Sort recycling for gardening that is a dependency here and tied to a Store cardboard for gardening and a Innoculate cardboard one @MorvinBear ?

**Comment by qubist** [comment]
This could be a time to follow the directive saying only use this tool as much as is needed, not more

**Comment by zippy** [comment]
Done!
